import swaggerJsdoc from 'swagger-jsdoc';
import path from 'path';

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: '3.0.3',
    info: {
      title: 'KDCL Groupage API',
      version: '1.0.0',
      description:
        'API REST du système de groupage KDCL — envoi de colis entre la Belgique et l\'Afrique.',
    },
    servers: [
      { url: '/api/v1', description: 'Serveur local' },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
      },
      schemas: {
        // Enums
        UserRole:      { type: 'string', enum: ['client', 'admin', 'freight_forwarder'] },
        UserStatus:    { type: 'string', enum: ['active', 'inactive', 'suspended'] },
        TravelStatus:  { type: 'string', enum: ['open', 'full', 'in_transit', 'at_warehouse', 'delivered', 'cancelled'] },
        TransportType: { type: 'string', enum: ['ship', 'plane'] },
        PackageStatus: {
          type: 'string',
          enum: ['pending', 'submitted', 'awaiting_payment', 'paid', 'in_travel', 'in_transit', 'at_warehouse', 'delivered', 'returned', 'cancelled'],
        },
        FragilityLevel: { type: 'string', enum: ['normal', 'fragile', 'tres_fragile'] },
        PaymentStatus:  { type: 'string', enum: ['pending', 'paid', 'failed', 'refunded', 'expired'] },
        PaymentProvider: { type: 'string', enum: ['stripe', 'notchpay'] },
        ReportTargetType: { type: 'string', enum: ['user', 'travel'] },
        ReportReason:     { type: 'string', enum: ['false_info', 'fraud', 'inappropriate', 'spam', 'other'] },
        ReportStatus:     { type: 'string', enum: ['pending', 'reviewed', 'dismissed'] },

        // Models
        User: {
          type: 'object',
          properties: {
            user_id:           { type: 'integer' },
            first_name:        { type: 'string' },
            last_name:         { type: 'string' },
            email:             { type: 'string', format: 'email' },
            phone:             { type: 'string' },
            street:            { type: 'string', nullable: true },
            city:              { type: 'string', nullable: true },
            country:           { type: 'string', nullable: true },
            postal_code:       { type: 'string', nullable: true },
            role:              { $ref: '#/components/schemas/UserRole' },
            status:            { $ref: '#/components/schemas/UserStatus' },
            registration_date: { type: 'string', format: 'date' },
            profile_picture:   { type: 'string', nullable: true },
            email_verified:    { type: 'boolean' },
            phone_verified:    { type: 'boolean' },
            createdAt:         { type: 'string', format: 'date-time' },
            updatedAt:         { type: 'string', format: 'date-time' },
          },
        },
        Country: {
          type: 'object',
          properties: {
            country_id: { type: 'integer' },
            name:       { type: 'string' },
            is_active:  { type: 'boolean' },
          },
        },
        Currency: {
          type: 'object',
          properties: {
            currency_id:  { type: 'integer' },
            code:         { type: 'string', example: 'EUR' },
            name:         { type: 'string', example: 'Euro' },
            symbol:       { type: 'string', example: '€' },
            rate_to_usd:  { type: 'number', format: 'double' },
            last_updated: { type: 'string', format: 'date-time' },
          },
        },
        Travel: {
          type: 'object',
          properties: {
            travel_id:               { type: 'integer' },
            created_by:              { type: 'integer' },
            transport_type:          { $ref: '#/components/schemas/TransportType' },
            origin_country_id:       { type: 'integer' },
            destination_country_id:  { type: 'integer' },
            itinerary:               { type: 'string', nullable: true },
            status:                  { $ref: '#/components/schemas/TravelStatus' },
            container:               { type: 'string', nullable: true },
            max_weight:              { type: 'number' },
            max_volume:              { type: 'number' },
            min_load_percentage:     { type: 'integer' },
            max_load_percentage:     { type: 'integer' },
            price_per_unit:          { type: 'number', nullable: true },
            creation_date:           { type: 'string', format: 'date' },
            departure_date:          { type: 'string', format: 'date', nullable: true },
            estimated_arrival_date:  { type: 'string', format: 'date', nullable: true },
            packages_count:          { type: 'integer' },
            current_weight:          { type: 'number' },
            current_volume:          { type: 'number' },
            weight_fill_pct:         { type: 'number' },
            volume_fill_pct:         { type: 'number' },
          },
        },
        Recipient: {
          type: 'object',
          properties: {
            recipient_id: { type: 'integer' },
            client_id:    { type: 'integer' },
            first_name:   { type: 'string' },
            last_name:    { type: 'string' },
            phone:        { type: 'string' },
            address:      { type: 'string' },
            city:         { type: 'string' },
            country:      { type: 'string' },
            email:        { type: 'string', format: 'email', nullable: true },
          },
        },
        Package: {
          type: 'object',
          properties: {
            package_id:             { type: 'integer' },
            client_id:              { type: 'integer' },
            travel_id:              { type: 'integer', nullable: true },
            recipient_id:           { type: 'integer' },
            tracking_number:        { type: 'string', example: 'PKG-1-1700000000000' },
            description:            { type: 'string' },
            weight:                 { type: 'number' },
            volume:                 { type: 'number' },
            declared_value:         { type: 'number' },
            status:                 { $ref: '#/components/schemas/PackageStatus' },
            fragility:              { $ref: '#/components/schemas/FragilityLevel' },
            price:                  { type: 'number', nullable: true },
            special_instructions:   { type: 'string', nullable: true },
            image1:                 { type: 'string', nullable: true },
            image2:                 { type: 'string', nullable: true },
            image3:                 { type: 'string', nullable: true },
            image4:                 { type: 'string', nullable: true },
            creation_date:          { type: 'string', format: 'date' },
            estimated_delivery_date:{ type: 'string', format: 'date', nullable: true },
            delivery_date:          { type: 'string', format: 'date', nullable: true },
          },
        },
        Payment: {
          type: 'object',
          properties: {
            payment_id:               { type: 'integer' },
            package_id:               { type: 'integer' },
            client_id:                { type: 'integer' },
            groupeur_id:              { type: 'integer' },
            travel_id:                { type: 'integer' },
            amount_usd:               { type: 'number' },
            platform_commission_rate: { type: 'number' },
            platform_commission_usd:  { type: 'number' },
            provider_fee_usd:         { type: 'number' },
            net_to_groupeur_usd:      { type: 'number' },
            provider:                 { $ref: '#/components/schemas/PaymentProvider' },
            provider_intent_id:       { type: 'string', nullable: true },
            receipt_url:              { type: 'string', nullable: true },
            status:                   { $ref: '#/components/schemas/PaymentStatus' },
            deadline_at:              { type: 'string', format: 'date-time' },
            paid_at:                  { type: 'string', format: 'date-time', nullable: true },
          },
        },
        Payout: {
          type: 'object',
          properties: {
            payout_id:         { type: 'integer' },
            travel_id:         { type: 'integer' },
            groupeur_id:       { type: 'integer' },
            gross_amount_usd:  { type: 'number' },
            provider_fee_usd:  { type: 'number' },
            net_amount_usd:    { type: 'number' },
            provider:          { $ref: '#/components/schemas/PaymentProvider' },
            status:            { type: 'string', enum: ['pending', 'processing', 'completed', 'failed'] },
            completed_at:      { type: 'string', format: 'date-time', nullable: true },
          },
        },
        Report: {
          type: 'object',
          properties: {
            report_id:    { type: 'integer' },
            reporter_id:  { type: 'integer' },
            target_type:  { $ref: '#/components/schemas/ReportTargetType' },
            target_id:    { type: 'integer' },
            reason:       { $ref: '#/components/schemas/ReportReason' },
            description:  { type: 'string', nullable: true },
            status:       { $ref: '#/components/schemas/ReportStatus' },
            creation_date:{ type: 'string', format: 'date' },
          },
        },
        Notification: {
          type: 'object',
          properties: {
            notification_id: { type: 'integer' },
            user_id:         { type: 'integer' },
            title:           { type: 'string' },
            content:         { type: 'string' },
            is_read:         { type: 'boolean' },
            creation_date:   { type: 'string', format: 'date-time' },
            pdf_file:        { type: 'string', nullable: true },
          },
        },
        PayoutAccount: {
          type: 'object',
          properties: {
            account_id:          { type: 'integer' },
            user_id:             { type: 'integer' },
            type:                { type: 'string', enum: ['iban', 'mobile_money'] },
            account_holder_name: { type: 'string' },
            iban:                { type: 'string', nullable: true },
            mobile_number:       { type: 'string', nullable: true },
            mobile_operator:     { type: 'string', enum: ['mtn', 'orange'], nullable: true },
            country_code:        { type: 'string' },
            is_default:          { type: 'boolean' },
            is_verified:         { type: 'boolean' },
          },
        },
        AdminStats: {
          type: 'object',
          properties: {
            users_count:         { type: 'integer' },
            travels_count:       { type: 'integer' },
            packages_count:      { type: 'integer' },
            total_revenue_usd:   { type: 'number' },
            users_by_role:       { type: 'object', additionalProperties: { type: 'integer' } },
            packages_by_status:  { type: 'object', additionalProperties: { type: 'integer' } },
          },
        },

        // Generic responses
        SuccessResponse: {
          type: 'object',
          properties: {
            status:  { type: 'string', example: 'success' },
            data:    { type: 'object' },
          },
        },
        ErrorResponse: {
          type: 'object',
          properties: {
            status:  { type: 'string', example: 'error' },
            message: { type: 'string' },
          },
        },
      },
    },
    security: [{ bearerAuth: [] }],
  },
  apis: [
    path.join(__dirname, '../modules/**/*.router.ts'),
  ],
};

export const swaggerSpec = swaggerJsdoc(options);
